Update install instructions with branch.
When running the original instructions I got this error:
```
cargo install --git https://github.com/roapi/roapi --bin roapi-http                                                                                                                                                                                                                                             
    Updating git repository `https://github.com/roapi/roapi`                                                                                                  
error: failed to find branch `master`                                                                                                                                                                                                                                                                                       
Caused by:                                                                                                                                                    
  cannot locate remote-tracking branch 'origin/master'; class=Reference (4); code=NotFound (-3) 
```

I believe `cargo` probably defaults to `master`, but since Github renamed `master` to `main` it broke things. The updated command, specifying `--branch main` seems to work for me.